import React from 'react'
import DummyNavbar from '../navbar/DummyNavbar'

import './Solutions.css'

import BioPanels1 from './BioPanels1.png'
import BioPanels2 from './BioPanels2.jpg'
import CarbonDrones from './Drones.png'
import FloatingFarm1 from './FloatingFarm1.png'
import FloatingFarm2 from './FloatingFarm2.jpg'
import ElectricBike from './ElectricBike.jpg'
import PeizoElectricSensors from './PeizoElectricSensors.png'
import MicroplasticRemoval from './MicroplasticRemoval.jpg'

export default function Solutions() {
    const solutions = [
        {
            name:"Floating Farm",
            description:"The world population has grown rapidly and is likely to exceed 8.5 billion people by 2030.  Food demand measured by population growth nearly doubled from 1966 to the present. \nOur solution to this problem is a floating farm. The Floating Farm aspires to bring food to people that do not have direct or indirect access to fertile soil for agriculture or conditions for farming. Our farm show how food production can become less vulnerable to climate change.  It also mitigates the negative impacts of natural disasters on food supply chains, like flooding. It avoids food waste and reduces its carbon footprint by producing and selling locally, and as a result, does not rely on long transportation paths.",
            images:[FloatingFarm1,FloatingFarm2]
        },
        {
            name:"Algae Bio-Panels",
            description:"Carbon dioxide (CO²) is the primary greenhouse gas emitted through human activities. In 2021, CO² accounted for 79% of all U.S. greenhouse gas emissions from human activities.  \nThat is why we have designed the algae bio-panels, which captures CO², produces oxygen and generates electricity! \nThese semi-transparent bio-panels, take a stream of carbon dioxide and combines it with nanofluids mixed with algae. In this process, the algae absorb the CO² and the sunlight, and photosynthesizes, increasing their mass and generating fresh oxygen. \nOur innovation here is in the thermal capture and conversion. The use of nanofluids – fundamentally, recyclable carbon nanoparticles are added to water, increasing its heat conductivity. This is run through one side of the panels, improving its heat capture, while the algae are grown on the other side. The heat in this case is transformed directly into electricity through a thermo-electric generator, and fed into the building, making these algae panels more analogous to traditional solar panels. These bio-panels also serve as a shade to the building, and as it captures heat, the air-conditioning costs are reduced. The biomass generated by the panels can be re-processed as biofuel as well. ",
            images:[BioPanels1,BioPanels2]
        },
        {
            name:"Carbon Capture Drones",
            description:"The long-term goals of the Paris Agreement are to hold the increase in the global average temperature to well below 2°C and to pursue efforts to limit the temperature increase to 1.5°C.  \nWe, Team Physis, present carbon capture drones and storage systems to get rid of up to 90% of the most common greenhouse gases produced in industrial and energy plants before they reach the atmosphere.   \nOur innovation is that the carbon dioxide gas then converts to solid carbon with the help of liquid catalysts, which operate at room temperature. \nThe carbon capture drones collect CO² and take it back to the station. While the drones recharge, a liquid metal electrocatalyst is used to convert carbon dioxide to solid carbon. We use a gallium-based alloy containing cerium to produce flakes of solid carbon. Gallium-based alloys are ideal for liquid metal electrocatalysts because they remain liquid at room temperature. This is economically feasible and easy to implement on a large scale.",
            images:[CarbonDrones]
        },
        {
            name:"Microplastic removal using Silica Gel",
            description:"Another environmental issue intensifying day by day is microplastics contaminating the water. Scientists estimate that there are at least 14 million metric tons of microplastics on the ocean floor, which are tough to detect and remove because of their minuscule size.  \nWe have come upon a solution to detect and remove these microplastics from the water. Discovered by a German non-profit Wasser 3.0, the process involves creating a vortex in a tank of water. \nThe main ingredient is a compound, a type of harmless hybrid silica gel called Wasser 3.0 PE-X. The hybrid silica gel consists of silicone-based chemicals called organosilanes and is non-toxic. The compound becomes attached to the surface of the microplastic particles and, when mixed, they quickly lump together and rise to the surface. It can be skimmed off using a sieve and be used for many different purposes.",
            images:[MicroplasticRemoval]
        },
        {
            name:"Electric Bikes",
            description:"Ever wondered if exercising could do more than strengthen our bodies? With our project, electric exercise bikes, your thought is transformed into reality. When in use, the pedals turn the handle which causes the alternator to spin, generating electricity, which is used to run lights and is also stored in the cell for when not in use.",
            images:[ElectricBike]
        },
        {
            name:"Peizo-electric sensors",
            description:"Currently, ⅛ of the global population lives without electricity, with most villages being completely in the dark. To combat this, we have devised a new way of generating electricity by using a piezo-electric generator, which converts mechanical energy, like footsteps, into electrical energy, which can be stored in a power station for further use.  \nWe embed the piezoelectric generator on the floor of public areas like marketplaces and railway stations. Here it can generate large amounts of electricity. The energy generated by this method is clean and affordable making rural communities self-sufficient while increasing their productivity and workforce.",
            images:[PeizoElectricSensors]
        },
    ]
  return (
    <div className='container-fluid p-md-5'>
        <DummyNavbar></DummyNavbar>
        {solutions.map((solution,id)=>(
        <div className={"d-flex align-items-center mb-4 flex-wrap flex-row"+(id%2===0?"":"-reverse")}>
            <div className="col col-md-4 col-12">
                {solution.images.map((image)=>(
                    <img src={image} alt={solution.name} className='w-100 mb-3'/>
                ))}
            </div>
            <div className="col">
                <h1 className='mx-auto text-center mt-5 mb-4 pink' id={solution.name.replace(" ","-")}>{solution.name}</h1>
                <p className='text-light text-left w-75 mx-auto solution-description display-linebreak'>
                    {solution.description}
                </p>
            </div>
        </div>))}
    </div>
  )
}
